### ISSUE TITLE
bulk_query empty at certain offsets

### ISSUE THREAD

**Issue by RiceCakess** [Tjstretchalot/USLBot-Site#1]
https://universalscammerlist.com/api/bulk_query.php?offset=4951
https://universalscammerlist.com/api/bulk_query.php?offset=5200
https://universalscammerlist.com/api/bulk_query.php?offset=5201

The offsets 4951~5200 return empty when queried.

**Comment by Tjstretchalot** [comment]
Hello,

The server appears to be having some difficulty serving all the requests, though I'm not sure why these offsets are consistently affected.

I changed the endpoint to reduce the load on the server and improve the response. It is unfortunately a (very slightly) breaking change, so I added a version parameter.

See the file for the new version information, but heres what you need to do to update:

- Add "version=2" as a parameter
- Query api/bulk_traditional.php for the full traditional list, which is the exact response you would have gotten from not specifying the offset before
- Rename offset to "start_id"
- If "response" is the top-level response from the server, use "response.data.bans" instead of "response.data"
- Instead of just incrementing offset, your next offset should be "response.data.next_id"
- Check for response 503 - you will receive this response when the bot is repropagating. fetching action information during this time is very expensive, so either fallback with an error or individual queries to query.php
Let me know if you have any trouble

**Comment by Tjstretchalot** [comment]
Since you will likely receive an email from this - I edited the post to fix a few typos and inaccuracies

EDIT: Noticed timestamp is returning as a string - that will be fixed in just a second here
EDIT: Fixed
